### ISSUE TITLE
[错误报告]我相信了你的"登录成功"....

### ISSUE THREAD

**Issue by RainYaya** [banned2054/Masiro2Epub#1]
### 当前程序版本

2.1.0

### 问题类型

登录问题

### 问题描述

熊猫流汗头.jpg，我竟然相信了你的"登录成功"...刚跑去这个网站注册,注册的时候没太放心上,看到右上角的名称以为是登录的用户名,嬉皮笑脸点击登录"登录成功"！好耶✌，访问书籍连接，“找到0个章节”。换一个连接，"找到0个章节"。visual studio启动！输入账号密码，登录成功。打开response一看，嗯?为啥没登录上去?我调啊调，找啊找，完全找不到问题所在,直到我打开浏览器，点击退出登录,重新登录的时候发现浏览器的账号记录另有其他，习惯性的以为名称可以登录。泪，流了下来。

**Comment by banned2054** [comment]
什么叫浏览器的账号记录另有其他，没看明白

**Comment by RainYaya** [comment]
> 什么叫浏览器的账号记录另有其他，没看明白

额.主要还是我输错了账号,注册账号的时候浏览器会保存注册信息的嘛,退出账号之后,这个注册信息也自动填充进去嘛,然后我才发现登录的账号并不是网站里的昵称..

**Comment by banned2054** [comment]
彳亍，你就是说让我整个登陆的验证嘛，登陆失败就不保存账号密码了，是这个意思对吧。。。说话别那么抽象

**Comment by banned2054** [comment]
解决：https://github.com/banned2054/Masiro2Epub/releases/tag/v2.2.0
