### ISSUE TITLE
[错误报告]抓取章节失败

### ISSUE THREAD

**Issue by nahakyuu** [banned2054/Masiro2Epub#2]
### 当前程序版本

master

### 问题类型

小说下载问题

### 问题描述

https://github.com/banned2054/Masiro2Epub/blob/acfec0d35d636f6741673b81b515e22e68468ee4/Masiro/lib/StringUnitTool.cs#L36-L64
在46行lineList重新变成null了，接下来的foreach就对象空了

### 小说下载网址

novel_id=336

### 小说下载出错的章节

cid=23399

**Comment by nahakyuu** [comment]
#3

**Comment by banned2054** [comment]
问题已解决
