### ISSUE TITLE
[错误报告]

### ISSUE THREAD

**Issue by SiliwWairon** [banned2054/Masiro2Epub#5]
### 当前程序版本

v2.2.0

### 问题类型

小说下载问题

### 问题描述

点击“访问”后无响应，一段时间后闪退
目前只有一部小说出现问题，试用其它的小说发现能正常解析

### 小说下载网址

https://masiro.me/admin/novelView?novel_id=752

### 小说下载出错的章节

目录无法加载出来

**Comment by banned2054** [comment]
最近会帮你看看

**Comment by banned2054** [comment]
https://github.com/banned2054/Masiro2Epub/releases/tag/v2.3.0
