### ISSUE TITLE
[错误报告]导出的时候自动闪退

### ISSUE THREAD

**Issue by Lin1nan279** [banned2054/Masiro2Epub#6]
### 当前程序版本

2.3.0

### 问题类型

小说下载问题

### 问题描述

导出每一章的时候，大约8%就会停止响应，然后闪退结束

### 小说下载网址

https://masiro.me/admin/novelView?novel_id=355

### 小说下载出错的章节

导出哪一章都是这样的结果

**Comment by banned2054** [comment]
目前确实导入不了，这个问题过段时间会修

**Comment by Lin1nan279** [comment]
好的！！真白萌导出EPUB这个软件好好用，不然一章章复制很要命，真的非常感谢您！


林依南
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "banned2054/Masiro2Epub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月5日(星期六) 晚上11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [banned2054/Masiro2Epub] [错误报告]导出的时候自动闪退 (Issue #6)





 
目前确实导入不了，这个问题过段时间会修

**Comment by banned2054** [comment]
问题已解决，看最新版release
