### ISSUE TITLE
[错误报告]登录失败捏

### ISSUE THREAD

**Issue by YURINdesu** [banned2054/Masiro2Epub#7]
### 当前程序版本

2.4.0

### 问题类型

登录问题

### 问题描述

登录失败，不会是网络问题吧
![QQ截图20240113200421](https://github.com/banned2054/Masiro2Epub/assets/156515354/ef302dec-efca-4407-966e-3a847e022146)

**Comment by banned2054** [comment]
看了下，真白萌加了bot识别，俺基本上解决不了，这个仓库估计是寄了

**Comment by YURINdesu** [comment]
> 看了一下，真白萌加了机器人识别，我基本解决不了，这个仓库估计是寄了

是嘛，那就没办法了。（头像是IA啊）

**Comment by banned2054** [comment]
> > 看了一下，真白萌加了机器人识别，我基本解决不了，这个仓库估计是寄了
> 
> 是嘛，那就没办法了。（头像是IA啊）

Sodayo
